export interface DidYouKnowCard {
  id: string;
  category: 'rights' | 'schemes' | 'safety' | 'civic' | 'environment';
  icon: string;
  titleEn: string;
  titleHi: string;
  bodyEn: string;
  bodyHi: string;
  keyPointHi: string;
  source: string;
}

export const didYouKnowCards: DidYouKnowCard[] = [
  // YOUR RIGHTS
  {
    id: 'rti-filing',
    category: 'rights',
    icon: '📋',
    titleEn: 'File RTI for Free',
    titleHi: 'मुफ्त में RTI दाखिल करें',
    bodyEn: 'You can file an RTI application online for free through the government portal. No need to visit any office physically.',
    bodyHi: 'आप सरकारी पोर्टल के माध्यम से मुफ्त में RTI आवेदन ऑनलाइन दाखिल कर सकते हैं। किसी भी कार्यालय में जाने की जरूरत नहीं।',
    keyPointHi: 'RTI आवेदन ऑनलाइन मुफ्त',
    source: 'rtionline.gov.in',
  },
  {
    id: 'consumer-rights',
    category: 'rights',
    icon: '🛡️',
    titleEn: 'Consumer Protection Rights',
    titleHi: 'उपभोक्ता संरक्षण अधिकार',
    bodyEn: 'If you receive defective goods or poor service, you can file a complaint in Consumer Court within 2 years of purchase.',
    bodyHi: 'यदि आपको खराब सामान या घटिया सेवा मिलती है, तो खरीद के 2 साल के भीतर उपभोक्ता न्यायालय में शिकायत दर्ज करा सकते हैं।',
    keyPointHi: 'खराब सामान की शिकायत 2 साल तक',
    source: 'consumerhelpline.gov.in',
  },
  {
    id: 'police-complaint',
    category: 'rights',
    icon: '🚨',
    titleEn: 'Police Complaint Rights',
    titleHi: 'पुलिस शिकायत अधिकार',
    bodyEn: 'Police cannot refuse to register an FIR for a cognizable offense. You can also file an online e-FIR for certain cases.',
    bodyHi: 'पुलिस कानूनी अपराध के लिए FIR दर्ज करने से इनकार नहीं कर सकती। कुछ मामलों के लिए ऑनलाइन e-FIR भी दर्ज कर सकते हैं।',
    keyPointHi: 'FIR दर्ज करने से इनकार नहीं',
    source: 'ncw.nic.in',
  },
  {
    id: 'grievance-redressal',
    category: 'rights',
    icon: '📮',
    titleEn: 'Grievance Redressal System',
    titleHi: 'शिकायत निवारण प्रणाली',
    bodyEn: 'Every government department has a grievance cell. You can submit complaints online and track their status.',
    bodyHi: 'हर सरकारी विभाग में शिकायत सेल है। आप ऑनलाइन शिकायत जमा कर सकते हैं और उनकी स्थिति ट्रैक कर सकते हैं।',
    keyPointHi: 'ऑनलाइन शिकायत ट्रैक करें',
    source: 'pgportal.gov.in',
  },

  // GOVT SCHEMES
  {
    id: 'pmay-scheme',
    category: 'schemes',
    icon: '🏠',
    titleEn: 'PMAY Housing Scheme',
    titleHi: 'PMAY आवास योजना',
    bodyEn: 'Pradhan Mantri Awas Yojana provides subsidized housing loans for low-income families. Eligible beneficiaries can get interest subsidy up to 6.5%.',
    bodyHi: 'प्रधानमंत्री आवास योजना कम आय वाले परिवारों को सब्सिडी वाले आवास ऋण प्रदान करती है। पात्र लाभार्थियों को 6.5% तक ब्याज सब्सिडी मिल सकती है।',
    keyPointHi: 'आवास ऋण पर सब्सिडी',
    source: 'pmaymis.gov.in',
  },
  {
    id: 'ayushman-bharat',
    category: 'schemes',
    icon: '🏥',
    titleEn: 'Ayushman Bharat Health',
    titleHi: 'आयुष्मान भारत स्वास्थ्य',
    bodyEn: 'Ayushman Bharat provides free health coverage up to ₹5 lakh per family per year for secondary and tertiary hospitalization.',
    bodyHi: 'आयुष्मान भारत प्रति परिवार प्रति वर्ष ₹5 लाख तक का मुफ्त स्वास्थ्य कवरेज प्रदान करता है।',
    keyPointHi: '₹5 लाख तक मुफ्त इलाज',
    source: 'pmjay.gov.in',
  },
  {
    id: 'pm-kisan',
    category: 'schemes',
    icon: '🌾',
    titleEn: 'PM-KISAN Scheme',
    titleHi: 'PM-KISAN योजना',
    bodyEn: 'Farmer families receive ₹6,000 per year in three installments directly in their bank accounts under PM-KISAN.',
    bodyHi: 'किसान परिवारों को PM-KISAN के तहत ₹6,000 प्रति वर्ष तीन किस्तों में सीधे बैंक खाते में मिलते हैं।',
    keyPointHi: '₹6,000 प्रति वर्ष किसानों को',
    source: 'pmkisan.gov.in',
  },
  {
    id: 'sukanya-samriddhi',
    category: 'schemes',
    icon: '👧',
    titleEn: 'Sukanya Samriddhi Yojana',
    titleHi: 'सुकन्या समृद्धि योजना',
    bodyEn: 'Parents of girl children below 10 years can open an account with high interest rate (8.2%) and tax benefits.',
    bodyHi: '10 साल से कम उम्र की बेटियों के माता-पिता उच्च ब्याज दर (8.2%) और कर लाभ के साथ खाता खोल सकते हैं।',
    keyPointHi: 'बेटियों के लिए 8.2% ब्याज',
    source: 'india.gov.in',
  },

  // SAFETY
  {
    id: 'women-helpline',
    category: 'safety',
    icon: '📞',
    titleEn: 'Women Helpline 181',
    titleHi: 'महिला हेल्पलाइन 181',
    bodyEn: 'Women in distress can call 181 toll-free for immediate assistance. The helpline operates 24/7 and connects to nearest police station.',
    bodyHi: 'परेशानी में महिलाएं तत्काल सहायता के लिए 181 टोल-फ्री नंबर पर कॉल कर सकती हैं। यह हेल्पलाइन 24/7 संचालित होती है।',
    keyPointHi: '24/7 महिला हेल्पलाइन',
    source: 'wcd.nic.in',
  },
  {
    id: 'child-helpline',
    category: 'safety',
    icon: '👶',
    titleEn: 'Child Helpline 1098',
    titleHi: 'बाल हेल्पलाइन 1098',
    bodyEn: 'Children in need of care and protection can call 1098. This toll-free number connects to Childline services across India.',
    bodyHi: 'देखभाल और सुरक्षा के लिए बच्चे 1098 पर कॉल कर सकते हैं। यह टोल-फ्री नंबर पूरे भारत में चाइल्डलाइन सेवाओं से जुड़ता है।',
    keyPointHi: 'बच्चों के लिए 1098 टोल-फ्री',
    source: 'childlineindia.org.in',
  },
  {
    id: 'emergency-number',
    category: 'safety',
    icon: '🆘',
    titleEn: 'Emergency Number 112',
    titleHi: 'आपातकालीन नंबर 112',
    bodyEn: 'India has a single emergency number 112 for police, fire, and ambulance. It works even without SIM card or balance.',
    bodyHi: 'भारत में पुलिस, अग्निशमन और एम्बुलेंस के लिए एक आपातकालीन नंबर 112 है। यह बिना SIM या बैलेंस के भी काम करता है।',
    keyPointHi: '112 - एक नंबर सभी आपातकाल',
    source: 'india.gov.in',
  },
  {
    id: 'cyber-crime',
    category: 'safety',
    icon: '💻',
    titleEn: 'Cyber Crime Reporting',
    titleHi: 'साइबर अपराध रिपोर्टिंग',
    bodyEn: 'Report cyber crimes online at cybercrime.gov.in. You can report financial fraud, social media crimes, and online harassment anonymously.',
    bodyHi: 'cybercrime.gov.in पर साइबर अपराधों की रिपोर्ट करें। आप वित्तीय धोखाधड़ी और ऑनलाइन उत्पीड़न गुमनाम रूप से रिपोर्ट कर सकते हैं।',
    keyPointHi: 'साइबर अपराध ऑनलाइन रिपोर्ट',
    source: 'cybercrime.gov.in',
  },

  // CIVIC TIPS
  {
    id: 'garbage-segregation',
    category: 'civic',
    icon: '🗑️',
    titleEn: 'Waste Segregation Rule',
    titleHi: 'कचरा अलगाव नियम',
    bodyEn: 'Segregate waste into wet (green bin) and dry (blue bin). Many cities impose fines for not segregating waste properly.',
    bodyHi: 'कचरे को गीला (हरा डिब्बा) और सूखा (नीला डिब्बा) में अलग करें। कई शहरों में ठीक से अलग न करने पर जुर्माना है।',
    keyPointHi: 'हरा-नीला डिब्बा जरूरी',
    source: 'swachhbharatmission.gov.in',
  },
  {
    id: 'water-harvesting',
    category: 'civic',
    icon: '💧',
    titleEn: 'Rainwater Harvesting',
    titleHi: 'वर्षा जल संचयन',
    bodyEn: 'Many Indian states mandate rainwater harvesting for buildings above certain plot size. It helps recharge groundwater.',
    bodyHi: 'कई भारतीय राज्यों में निश्चित भूखंड आकार से ऊपर की इमारतों के लिए वर्षा जल संचयन अनिवार्य है।',
    keyPointHi: 'वर्षा जल संचयन अनिवार्य',
    source: 'cgwb.gov.in',
  },
  {
    id: 'noise-rules',
    category: 'civic',
    icon: '🔇',
    titleEn: 'Noise Pollution Limits',
    titleHi: 'ध्वनि प्रदूषण सीमा',
    bodyEn: 'Loudspeakers are not permitted between 10 PM and 6 AM. Firecrackers have time restrictions during festivals.',
    bodyHi: 'रात 10 बजे से सुबह 6 बजे के बीच लाउडस्पीकर की अनुमति नहीं है। त्योहारों के दौरान पटाखों पर समय प्रतिबंध है।',
    keyPointHi: 'रात 10 बजे के बाद लाउडस्पीकर नहीं',
    source: 'cpcb.nic.in',
  },
  {
    id: 'property-tax',
    category: 'civic',
    icon: '🏛️',
    titleEn: 'Property Tax Rebate',
    titleHi: 'संपत्ति कर छूट',
    bodyEn: 'Many municipalities offer 5-10% rebate on property tax for early payment. Pay online to avoid queues and get discounts.',
    bodyHi: 'कई नगरपालिकाएं जल्दी भुगतान पर संपत्ति कर में 5-10% छूट देती हैं। ऑनलाइन भुगतान करें और छूट पाएं।',
    keyPointHi: 'जल्दी भुगतान पर छूट',
    source: 'mohua.gov.in',
  },

  // ENVIRONMENT
  {
    id: 'plastic-ban',
    category: 'environment',
    icon: '🚫',
    titleEn: 'Single-Use Plastic Ban',
    titleHi: 'सिंगल-यूज प्लास्टिक प्रतिबंध',
    bodyEn: 'India has banned single-use plastic items below 100 microns thickness. Violators can face fines up to ₹5,000.',
    bodyHi: 'भारत ने 100 माइक्रोन से कम मोटाई वाले सिंगल-यूज प्लास्टिक आइटम पर प्रतिबंध लगा दिया है। उल्लंघनकर्ताओं पर ₹5,000 तक जुर्माना हो सकता है।',
    keyPointHi: 'प्लास्टिक पर ₹5,000 जुर्माना',
    source: 'moefcc.gov.in',
  },
  {
    id: 'tree-cutting',
    category: 'environment',
    icon: '🌳',
    titleEn: 'Tree Cutting Permission',
    titleHi: 'पेड़ काटने की अनुमति',
    bodyEn: 'Cutting trees without permission is illegal. You need permission from the municipal corporation or forest department.',
    bodyHi: 'बिना अनुमति के पेड़ काटना गैरकानूनी है। नगर निगम या वन विभाग से अनुमति लेनी होगी।',
    keyPointHi: 'पेड़ काटने के लिए अनुमति जरूरी',
    source: 'moefcc.gov.in',
  },
  {
    id: 'green-tribunal',
    category: 'environment',
    icon: '⚖️',
    titleEn: 'Green Tribunal Access',
    titleHi: 'ग्रीन ट्रिब्यूनल पहुंच',
    bodyEn: 'Any citizen can approach the National Green Tribunal for environmental violations without hiring a lawyer.',
    bodyHi: 'कोई भी नागरिक वकील किराए पर लिए बिना पर्यावरण संबंधी उल्लंघन के लिए राष्ट्रीय हरित अधिकरण से संपर्क कर सकता है।',
    keyPointHi: 'वकील के बिना पर्यावरण मामला',
    source: 'greentribunal.gov.in',
  },
  {
    id: 'e-waste-disposal',
    category: 'environment',
    icon: '🔋',
    titleEn: 'E-Waste Disposal Rules',
    titleHi: 'ई-वेस्ट निपटान नियम',
    bodyEn: 'Electronic waste must be disposed at authorized collection centers. Dumping e-waste in regular garbage can attract fines.',
    bodyHi: 'इलेक्ट्रॉनिक कचरा अधिकृत संग्रह केंद्रों पर ही निपटाया जाना चाहिए। सामान्य कचरे में फेंकने पर जुर्माना हो सकता है।',
    keyPointHi: 'ई-वेस्ट अधिकृत केंद्र पर दें',
    source: 'cpcb.nic.in',
  },
];

export const categoryLabels = {
  all: { en: 'All', hi: 'सभी' },
  rights: { en: 'Your Rights', hi: 'आपके अधिकार' },
  schemes: { en: 'Govt Schemes', hi: 'सरकारी योजनाएं' },
  safety: { en: 'Safety', hi: 'सुरक्षा' },
  civic: { en: 'Civic Tips', hi: 'नागरिक सुझाव' },
  environment: { en: 'Environment', hi: 'पर्यावरण' },
};
